// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gehhauoymmlvbzxcoqbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlaGhhdW95bW1sdmJ6eGNvcWJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NzU0MTcsImV4cCI6MjA2MTE1MTQxN30.QqWqIfZRpH2ibUpRirzYDTjPX2-cIgwyZ5fevGyrltE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);